### ISSUE TITLE
Question: Should redispatch be extended to allow a target to be specified

### ISSUE THREAD

**Issue by matthewdunsdon** [zambezi/d3-utils#17]
The man page for redirect states
> Allows the consolidation of event APIs from multiple components for easier component composition.
>
> ... a unified dispatcher can be created,
>
> ... so that the client can attach all the handlers at one level,

I am not sure whether adding the ability to specify a target (to an existing component or dispatcher), would be fitting the purposes of the redirect module / function, therefore I want to open the floor to a discussion.

## Context

I would like to be able to write code like the following:

```javascript
const events = redispatch()
          .from(a, 'a', 'b')
          .from(b, 'd', 'e')
          .from(c, 'f')
        .target(existingDispatcher)

// expect: events === existingDispatcher
```

This would allow me to write code where it could create (or take in existing) event sources and extend (or provide a wrapper) for an existing dispatcher or component. To do this, I would need to be able to specify that that events will be redispatched from one or more dispatcher(s) **to an existing dispatcher**.

**Comment by mstade** [comment]
So you want to extend an existing dispatcher with additional events? What's the use case? Could this be a new dispatcher, just that it *also* forwards *all* events from one (or more?) existing dispatchers?

So something like:

```javascript
const events = redispatch()
    .from(a, 'a', 'b')
    .from(b, 'd', 'e')
    .from(c, 'f')
    .from(existingDispatcher, redispatch.all)
```

Where `redispatch.all` is some marker object that redispatch understands to mean "redispatch all of the things". Not sure this can be done, but if you don't *need* to mutate the existing dispatcher it might be worth considering.

**Comment by gabrielmontagne** [comment]
How are you guys thinking of doing it? There's no introspection possible on
these dispatchers.

**Comment by matthewdunsdon** [comment]
_To clarify:_ No, I do not want to extend an existing dispatcher with additional events.

I want to redispatch from one or more dispatcher(s) to an existing dispatcher _which already is known to have these events_.

Basically I want to use redispatch to:

```javascript
// some-file.js
import { dispatch } from 'd3-dispatch'
import myWrapper from './my-wrapper'

const myDispatcher= dispatch('a', 'b', 'c', 'd', 'e')
// Do extra stuff with myDispatcher

const response = myWrapper(myDispatcher)

export default response
```

```javascript
// my-wrapper.js
import { dispatch } from 'd3-dispatch'
import { redispatch } from 'd3-utils'

export default function myWrapper(dispatcher) {
  const a = dispatch('a', 'b', 'c')
    , b = dispatch('d', 'e')
    , c = dispatch('f')

  return redispatch()
    .from(a, 'a', 'b')
    .from(b, 'd', 'e')
    .from(c, 'f')
    .target(existingDispatcher)
}
```

Otherwise I have to write:

```javascript
// my-wrapper.js
import { dispatch } from 'd3-dispatch'

export default function myWrapper(dispatcher) {
  const a = dispatch('a', 'b', 'c')
    , b = dispatch('d', 'e')
    , c = dispatch('f')

  a.on('a', (...args) => { dispatcher.apply('a', null, args) })
  a.on('b', (...args) => { dispatcher.apply('b', null, args) })
  a.on('c', (...args) => { dispatcher.apply('c', null, args) })
  b.on('d', (...args) => { dispatcher.apply('d', null, args) })
  b.on('e', (...args) => { dispatcher.apply('e', null, args) })
  c.on('f', (...args) => { dispatcher.apply('f', null, args) })

  return dispatcher
}
```

**Comment by matthewdunsdon** [comment]
For a more concrete example of the issue I am facing, consider <https://github.com/zambezi/d3-utils/pull/16#issuecomment-304050596>

Given I have an inflight implementation:
- if new request then it returns a new dispatcher
- if request is not new then it returns the correct existing dispatcher

```javascript
const inflightRequest = inflight(key, 'beforesend', 'progress', 'load', 'error')
```

In this example, I now have a dispatcher (that another piece of code has created) that need to be hooked up for new requests. I also want to use libraries like `d3.json` have their own events ('beforesend', 'progress', 'load', 'error'), so I would like to wire them up to the dispatcher returned by `inflight`.  

Questions:

1. In this case, does it make sense to say that I want to redispatch the `d3.json` events to my `inflight` dispatcher, or is "redispatch" the wrong word?
2. To me the design of the `inflight` module seems like a good design, but it does not allow us to using any existing d3-utils function, because the dispatcher gets created by the module.  Is this an indication there is something wrong with my design?
