### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by mstade** [zambezi/d3-utils#6]
@gabrielmontagne I'm going to enable protected branches, so we can't push directly to master. I've found this increases confidence in the master branch _a lot_, but comes with some caveats. For instance, version bumps has to happen on the feature branch you're working on before merging. I find this makes sense anyway, since that's where the relevant change happens. This means master will from now on _only_ be merge commits. With some proper commit message hygiene, it should make it trivial to generate change logs in between version tags (just collate the merge commits in between two tags.)

**Comment by gabrielmontagne** [comment]
@mstade , sounds good. Go for it.

**Comment by gabrielmontagne** [comment]
... but the problem of tagging on the branch is that the order in which PRs are merged can mess up other PRs in flight, or the order of the release tags.  Tags cut across the whole repo and are not contained in a branch, do they?

**Comment by gabrielmontagne** [comment]
... we can agree to not push anything directly to master, but still tag there.  what do you think @mstade?
Like grownups ; )

**Comment by gabrielmontagne** [comment]
chatting offline with @mamapitufo , if we tag on a branch, let's say, v2.0.0 or whatever.  Even if that branch is not merged, the tag "is taken".  So we'd have to sync and do PRs from remote repos.

**Comment by mamapitufo** [comment]
I guess you could do something that can be described as "release in a branch":

``` sh
git branch release-x.x.x
git checkout release-x.x.x
npm version x.x.x
git commit -am 'Release x.x.x`
git checkout master
git merge release-x.x.x
npm publish
git tag release-x.x.x
```

The order of some of these things could be different, but the general idea should work. This would allow you to protect the master branch without changing how you handle feature branches.

**Comment by mamapitufo** [comment]
You could copy the body of the PR for these 'release branches' to the description of your releases. Or collect any PRs in between these PRs (or release tags).

**Comment by mstade** [comment]
> [...] if we tag on a branch, let's say, v2.0.0 or whatever. Even if that branch is not merged, the tag "is taken". So we'd have to sync and do PRs from remote repos.

That's the point entirely. Ideally, you tag with a prerelease label during development, to indicate which version you're gunning for. This is enough I think to signal to others what's going on. Even if someone else is gunning for the same version (this probably happens more often with patches than anything else) that's ok, because whoever gets their stuff pushed first will win, and the other will get an error if they try to push, have to clean up a little bit then push a new patch version. Sure, if we had tens or hundreds of developers pushing new version _all of the time_ this would be an issue that could take some time to settle, but we don't, and it isn't. :o)

Keeping the tagging and everything on the branches mean there's 100% traceability to when and where things changed, which you lose if you merge-then-tag – particularly if there are mistakes made when tagging.

Besides, if you do the tagging on the master branch you'd still have the same issue if people want to tag at the same time, just in a different place and with worse traceability.

If we would like to get all fancy with it, it's not difficult to implement a status check that would do some version validation, like requiring you to bump the version (but not do it for you, so as to stay read-only) and requiring you to strip prerelease tags before merging to master. It'd have to be hosted somewhere though (or it could be baked into a Travis script I guess.)

**Comment by mstade** [comment]
To describe the workflow:
1. Checkout a feature branch
2. Do work
3. Cut a prerelease and push (let's say `1.0.0-branch-name.0` – the `branch-name` can be anything, but making it the same as the branch name makes it cognitively easy to know where it's from, `.0` is the sequence number of this version, with `.0` being the first prerelease, `.1` being the second and so on)
4. Done? goto 5 : goto 2
5. Cut a master release and push (in this case `1.0.0`)
6. Merge to master

Master would then always look something like this:

```
---o--o----o
-a/  /    /
--- / --b/
--c/
```

Where `o` are merge commits and `a`, `b`, and `c` are tags. Now, to get a change log of `a -> c` I just get the merge commits between these versions and hey presto, there's my log. (Provided these merge commits have any reasonable messages that is, but that can be manufactured after the fact too, if need be.)

Of course, this can be done otherwise too, but I find this the cleaner than having something like this:

```
---oa-oc---ob
--/  /    /
--- / ---/
---/
```

As well, it would remove the chance of this unfortunate situation:

```
---o--oac---ob
--/  /     /
--- / ----/
---/
```

Of course, this can and should be avoided by tagging specific SHAs, but let's be honest – we all just assume `HEAD` anyway, and cleanups are boring. :o)

**Comment by mstade** [comment]
Btw, I use [prepare-release](https://github.com/zambezi/prepare-release) when implementing this workflow – makes it a breeze!

**Comment by mamapitufo** [comment]
that would work as well, and if you already have the tool that does all the plumbing, much better!

**Comment by mstade** [comment]
You should try it @mamapitufo, you'll like it. :o)

This is what I do in command terms:

``` bash
$ git checkout -b branch-name
Switched to a new branch 'branch-name'

$ subl .

# Doing a bunch of work

$ git commit -am "Committing some changes"
[branch-name 24e5a28] Committing some changes
 1 file changed, 2 insertions(+)

$ prepare-release 
v1.0.1-branch-name.0

$ git push origin branch-name --follow-tags
```

And when I'm ready to go to master:

``` bash
$ prepare-release master
v1.0.1

$ git push origin branch-name --follow-tags
```

More over, with a setup in Travis CI (or other CI) to deploy all tags things will automagically be in npm as well, whenever a semver tag is pushed. (And in [GitHub releases](https://github.com/zambezi/ez-build/releases) as well!)

**Comment by gabrielmontagne** [comment]
So, just to confirm, @mstade ,  we're on version `2.1.0` released and good, 
1. You start a new `fancy-feature`, so you start releasing `2.2.0-fancy-feature.0`
2. @mamapitufo starts working on `another-thing`, and starts releasing `2.2.0-another-thing.0`
3. He actually finishes first, so `2.2.0` is released and has "another thing" in it.
4. Your next release will be `2.3.0-fancy-feature.0`, right?  And so on until you're done?

**Comment by mstade** [comment]
Yup.

Now, one thing this does lead to is a proliferation of prerelease tags. I've not seen this as a problem yet, but I can see how it could be if you'd like to only show or deploy "real" tags. For instance, on ez-build we deploy _all_ tags, from _anywhere_. It'd be trivial to change this to only deploy from specific branches, but that takes away the ability to easily push prerelease versions. After all, part of the point of prerelease versions is to get them out in the wild to test before you go live. But once they are live, you kind of don't care about the prerelease versions, so it'd be nice to clean that up. But that would mean removing tags from git, and unpublishing artifacts – is that really kosher?

**Comment by gabrielmontagne** [comment]
... Ok, @mstade, I'm preparing a new PR on the grid, I should tag for the new release branch on that branch. If you guys reject my PR, tho, that tag will already be taken.   Is that _fine_, let's say, on your workflow? Or are you expecting we always create PRs from forks? -- still tags wouldn't jump across, would they?

**Comment by mstade** [comment]
Tags only matter in this repo, if you tag in a fork it's irrelevant really, unless you also push that tag here. But yes, if the PR is rejected, the tag will be "taken". This is why we use prerelease labels, but also comes back to the question of what to do with tags that aren't really necessary anymore. For example, we remove branches that have been merged, or simply aren't necessary anymore – should we do a similar thing for tags? That is, remove any prerelease tags once merged to master; or indeed if the PR is rejected? I'm ok with this, but it has further implications beyond just the repo – things like prereleases published to npm should probably also be unpublished then.

What are your thoughts?

**Comment by gabrielmontagne** [comment]
I don't mind "proliferation of pre-release tags" at all,
actually I like having pre-releases with "try out this `fancy-thing` that'll likely be in 2.4.0", by publishing `2.4.0-fancy-thing.2`.   

But where is the `2.4.0` with no suffixes tagged? I'm not sure, but I don't think it's responsibility of whoever is doing the fix or the feature, the missing leading semicolon added, to know the release strategy of the main project -- who knows if they want to bundle a bunch of things into one minor release?  Not me, the lowly contributor.  

TBH, to have to review `package.json` versions on PRs sounds like too much, and no one expects to have to deal with that admin crap when doing a fix or whatever.

After all this back-and-forth, I personally prefer to agree with contributors not to push directly to master -- and do their "branch qualified" prereleases from branches if needed.  But then have "real versions" committed and tagged by TC (or whoever is temporarily doing that CI job manually), on master after the merge, when what's going out is known.

Otherwise it'll be release branches and all that, that starts to sound way to enterprisey for these still 2~3 people (adults) per repo which we currently have.

**Comment by mstade** [comment]
> But where is the 2.4.0 with no suffixes tagged? I'm not sure, but I don't think it's responsibility of whoever is doing the fix or the feature, the missing leading semicolon added, to know the release strategy of the main project -- who knows if they want to bundle a bunch of things into one minor release? Not me, the lowly contributor.

I understand your point, but I don't think it's really that big of a deal. If we're talking about a fork, then whatever you do in your fork doesn't matter to me as a project maintainer. Likewise, as you say, it's up to me as a project maintainer to figure out whatever my release strategy is. I advocate a strategy where branches are self contained – there's no change, including tagging, happening outside of that branch. This makes it easier to track the cause and effect of things. Now, for the situation where you have a prerelease on one branch, but you want to combine it with the release of something else, to me that's just a matter of merging into another branch than master. The version-on-the-branch stance remains, but it may be that you never get to a _final_ version on a given branch, because it was merged into something else.

Point is, master is the canonical story of the repo, with individual branches being like little side quests that happened to come back around (or not!)

> TBH, to have to review package.json versions on PRs sounds like too much, and no one expects to have to deal with that admin crap when doing a fix or whatever.

I disagree, I think it's part of the whole dance, and is borne out of the point of view that branches are self contained units of change. I think you should be able to ignore a branch altogether, and the world isn't particularly different for it. I just find it easier to reason about. I may be wrong.

> But then have "real versions" committed and tagged by TC (or whoever is temporarily doing that CI job manually), on master after the merge, when what's going out is known.

So long as I have any say in anything, automated tools will _never_ push back to source. I don't particularly like versions (although I like SHAs) but what I dislike more is when you relinquish what is essentially a UX concern to tooling with inevitably poor heuristics.

Listen, I don't want to complicate matters but it seems like maybe I am. I'll just close this and open a PR on the Zambezi project template to add some git hooks I think might be meaningful, then we can discuss more concretely there. :o)
